spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memories
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
      jdbc:
        lob:
          non_contextual_creation: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

bot:
  name: my_spring_boot_bot
  token: 6166202220:AAH2P8FJWFpniQz-yZuQIS--vzySh_Ta_uo