server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://172.21.0.2:5432/memories
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
      jdbc:
        lob:
          non_contextual_creation: true
    show-sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB


#swagger-ui config
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoint:
    health:
      show-details: always
    beans:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus