server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memories
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
