server:
  port: 8086

redis:
  host: redis
  port: 6379
  password: test123
  cache:
    type: redis

bot:
  name: my_spring_boot_bot
  token:
api:
  host:
    baseurl: http://rest-service:8085/v1/words