server:
  port: 8086

redis:
  host: localhost
  port: 6379
  password: test123
  cache:
    type: redis

bot:
  name: my_spring_boot_bot
  token: 6166202220:AAHjOuEIb3m_vx-lDvAZQyG-tCykb7h1jw4

api:
  host:
    baseurl: http://localhost:8085/v1/words