name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create log directory
      run: mkdir -p logs/com/example/demo/memories

    - name: Create log file
      run: touch logs/com/example/demo/memories/app.log
      
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        cache: maven
        
    - name: Print PostgreSQL container IP
      run: |
        echo "Container ID: $(docker-compose ps -q postgres)"
        echo "Container IP: $(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker-compose ps -q postgres))"

    - name: Build with Maven
      run: mvn clean install

    - name: Run integration tests
      run: mvn verify -Pintegration-test
      
