name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    services:
          postgres:
            image: postgres:13.3
            ports:
              - 5432:5432
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: 123
              POSTGRES_DB: memories
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create log directory
      run: mkdir -p logs/com/example/demo/memories

    - name: Create log file
      run: touch logs/com/example/demo/memories/app.log
      
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        cache: maven
    - name: Start PostgreSQL container
      run: |
        docker run -d --name postgres-container -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=123 -e POSTGRES_DB=memories postgres:13.3
        sleep 10
                
    - name: Print PostgreSQL container IP
      run: |
          echo "Container IP: $(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgres-container)"
   
    - name: Build with Maven
      run: mvn clean install

    - name: Run integration tests
      run: mvn verify -Pintegration-test
      
